name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: ["20", "24"]
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Node Dependencies
        run: npm ci --ignore-scripts
      - name: Install System Dependencies
        if: matrix.os == 'ubuntu'
        run:
          sudo apt-get update && sudo apt-get install -y xorg-dev
          libglu1-mesa-dev
      - name: Build Node Addon
        run: npm run compile
      - name: Test
        run: npm test

  build-linux-arm:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm
            platform: linux/arm/v7
            runner: ubuntu-latest
            variant: standard
            script: ./tools/crossbuild.sh
          - arch: arm
            platform: linux/arm/v7
            runner: ubuntu-latest
            variant: drm
            script: ./tools/crossbuild-drm.sh
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-latest
            variant: standard
            script: ./tools/crossbuild.sh
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-latest
            variant: drm
            script: ./tools/crossbuild-drm.sh
          - arch: arm64
            platform: native
            runner: ubuntu-24.04-arm64
            variant: standard
            script: native
    runs-on: ${{ matrix.runner }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        if: matrix.platform != 'native'
        uses: docker/setup-qemu-action@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install Node Dependencies (native)
        if: matrix.platform == 'native'
        run: npm ci --ignore-scripts
      - name: Install System Dependencies (native)
        if: matrix.platform == 'native'
        run: |
          sudo apt-get update && sudo apt-get install -y xorg-dev libglu1-mesa-dev cmake build-essential
      - name: Build Node Addon (native)
        if: matrix.platform == 'native'
        run: npm run compile
      - name: Build for ${{ matrix.arch }} (${{ matrix.variant }})
        if: matrix.platform != 'native'
        run: |
          docker run --platform ${{ matrix.platform }} --rm -v "${PWD}:/work" -w /work node:20-bullseye ${{ matrix.script }}
